blank_issues_enabled: false
contact_links:
  - name: I'm unsure where to go
    url: https://gitter.im/picklepete/pyicloud
    about: If you are unsure where to go, then joining our chat is recommended; Just ask!
